# SPDX-FileCopyrightText: 2026 Anemoi contributors
#
# SPDX-License-Identifier: Apache-2.0

"""Anemoi-datasets source plugin for extraterrestrial datasets."""

try:
    # NOTE: the `_version.py` file must not be present in the git repository
    #   as it is generated by setuptools at install time
    from ._version import __version__
except ImportError:  # pragma: no cover
    # Local copy or not installed with setuptools
    __version__ = "999"

__all__ = ["__version__"]
