# SPDX-FileCopyrightText: 2026 Anemoi contributors
# SPDX-License-Identifier: Apache-2.0
#
# This workflow assigns labels to a pull request based on the files changed in the PR.
# The labels are defined in the `.github/labeler.yml` file.
name: "[PR] Label File-based"
on:
  pull_request_target:
    types: [opened, synchronize]

permissions:
  contents: read

jobs:
  labeler:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
    - name: Assign labels from file changes
      uses: actions/labeler@bf12e9b00b37c5c0ca2b87b79b2daf7891dbda13  # v7.0.0
