# SPDX-FileCopyrightText: 2026 Anemoi contributors
# SPDX-License-Identifier: Apache-2.0
#
# Manage labels of pull requests that originate from forks.
name: "[PR] Label Forks"

on:
  pull_request_target:
    types: [opened, synchronize]

jobs:
  label:
    uses: ecmwf/reusable-workflows/.github/workflows/label-pr.yml@v2
