# SPDX-FileCopyrightText: 2026 Anemoi contributors
# SPDX-License-Identifier: Apache-2.0
#
# Manage labels of pull requests that originate from forks.
name: "[PR] Label Forks"

on:
  pull_request_target:
    types: [opened, synchronize]

permissions:
  contents: read
  pull-requests: write

jobs:
  label:
    uses: ecmwf/reusable-workflows/.github/workflows/label-pr.yml@592e3dd68954d6c84039f3d9343adef8da264686  # v2
