# SPDX-FileCopyrightText: 2026 Anemoi contributors
# SPDX-License-Identifier: Apache-2.0
#
# Manage labels of pull requests that originate from forks.
name: "[PR] Label Forks"

on:
  pull_request_target:
    types: [opened, synchronize]

permissions:
  contents: read
  pull-requests: write

jobs:
  label:
    uses: ecmwf/reusable-workflows/.github/workflows/label-pr.yml@d1569ef93dd05b6c40f4d1700346cc2fcb61a486  # v2
