# SPDX-FileCopyrightText: 2026 Anemoi contributors
# SPDX-License-Identifier: Apache-2.0
#
# This workflow runs pre-commit checks and pytest tests against multiple platforms and Python versions.
name: Code Quality and Testing

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - main
  schedule:
    - cron: "9 2 * * 0" # at 9:02 on sunday

permissions:
  contents: read

jobs:
  quality:
    uses: ecmwf/reusable-workflows/.github/workflows/qa-precommit-run.yml@631d38ab6601b12c7b5a51d4dd55dac5aa6702eb  # v2
    with:
      skip-hooks: "no-commit-to-branch"

  checks:
    strategy:
      matrix:
        python-version: ["3.12", "3.13"]
    uses: ecmwf/reusable-workflows/.github/workflows/qa-pytest-pyproject.yml@6441ce75e023ec2cbcdc546bd45832d561f5f432  # v2
    with:
      python-version: ${{ matrix.python-version }}
